### PR TITLE
Initial documentation - Contributing

### PR DESCRIPTION
**Pull request by V3ntus**
- Created and filled (incomplete) `CONTRIBUTING.md` 
(because documentation is extremely important)

### CODE REVIEW

**Comment by V3ntus** [comment]
Oh hm. Accidentally included my actions setup yml in there for pylint. I'll leave that to you to consider, but you're definitely welcome to close without merge

**Comment by savioxavier** [comment]
The contributions seem fine, but is there any way you could remove the `pylint.yml` file as I don't really require it and I usually lint files before commiting?

**Comment by V3ntus** [comment]
Ok so I don't know how to use git apparently. WIP

**Comment by mauvehed** [comment]
> Ok so I don't know how to use git apparently. WIP

Every so often I get to a point of totally screwing up a PR that I just have to start over. It happens 😁

**Comment by savioxavier** [comment]
> Ok so I don't know how to use git apparently

I feel you man, happens to me a lot. Had to delete entire branches once cause I screwed up everything.

**Review by savioxavier — APPROVED** [review]

**Pull request merged**
