### PR TITLE
Complete code restructure

### PR DESCRIPTION
**Pull request by V3ntus**
## Changelog for ba5ba59
Previous commits pertain to previous PRs and should be reviewed first

Ultimately, this is a complete re-organization of code

### CODE REVIEW

**Comment by savioxavier** [comment]
Looks alright, might need to update your `code-restructure` branch, considering I just merged your previous PR.

Also, I like the fact that cogs will now be dynamically loaded along with cog exception handling. Neat.

**Comment by savioxavier** [comment]
This certainly has come a long way since the initial commits 4e4c0795defedb5860ec5286950eecc55720538a

Could you please elaborate why exactly is `src` chosen as the folder inside `cogs`? Might be because I'm used to seeing `src` at the root on most repositories, but this will do just fine, I guess

Also will this restructure make it easier to add slash commands (at a later date, of course)?

**Comment by V3ntus** [comment]
> This certainly has come a long way since the initial commits 4e4c0795defedb5860ec5286950eecc55720538a
> 
> Could you please elaborate why exactly is `src` chosen as the folder inside `cogs`? Might be because I'm used to seeing `src` at the root on most repositories, but this will do just fine, I guess
> 
> Also will this restructure make it easier to add slash commands (at a later date, of course)?

Yeah I think the directory structure could be improved, or maybe not. Not sure. `src` acts as a source tree for the cogs to reference to, not so much for other code.

I'm not very familiar with slash command implementation so I'll have to research that. I should add, cog commands are both dynamically loaded as extensions *and* native Python modules (not great practice probably), so theoretically this could make it easier

**Comment by savioxavier** [comment]
Alright then, take your time. No rush 👍

**Comment by savioxavier** [comment]
> I'm not very familiar with slash command implementation so I'll have to research that.

Slash commands are pretty easy to add. I've been thinking of doing it myself, however I'm not sure where to place them, considering the current code structure, as it might involve duplicate code.

**Comment by V3ntus** [comment]
> Slash commands are pretty easy to add. I've been thinking of doing it myself, however I'm not sure where to place them, considering the current code structure, as it might involve duplicate code.

Hm. I'm not sure which route you'll take. I noticed an import for slash_commands, but not sure if this is the same library
https://discord-py-slash-command.readthedocs.io/en/latest/faq.html#will-discord-py-be-able-to-work-with-this-library

**Comment by savioxavier** [comment]
>Hm. I'm not sure which route you'll take. I noticed an import for slash_commands, but not sure if this is the same library
https://discord-py-slash-command.readthedocs.io/en/latest/faq.html#will-discord-py-be-able-to-work-with-this-library

That doesn't look like the same library. The one I wanted to use is at: https://github.com/goverfl0w/discord-interactions
The docs are at https://discord-interactions.readthedocs.io/en/latest/

I do know how to use this library and I have a "prototype" of the slash commands on a local branch. I might modify it a bit and push it to `main` later. As of now, the main aim is to update the code structure and merge this PR.

**Review by savioxavier — APPROVED** [review]

**Comment by savioxavier** [comment]
Perfect! It works.

Might refactor, lint and format the code later.

Merged!

**Comment by V3ntus** [comment]
Awesome!

**Pull request merged**
